### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by raiyeeeric** [raiyeeeric/stylus-assist#2]
![image](https://user-images.githubusercontent.com/13230237/34660350-9395c908-f47c-11e7-8f47-a383aabcf18e.png)

**Comment by raiyeeeric** [comment]
![wechatimg73](https://user-images.githubusercontent.com/13230237/35953873-b0277e4c-0cc1-11e8-9482-5962fe0bedab.jpeg)

**Comment by raiyeeeric** [comment]
![image](https://user-images.githubusercontent.com/13230237/35954042-88d45846-0cc2-11e8-98a3-29adb4f0be9a.png)

**Comment by gucovip** [comment]
![coffee](https://user-images.githubusercontent.com/13230237/128452500-292addd6-8bd6-42f1-aa9f-547341b0cb1e.png)
